const sheet = wb.Worksheets.Item(params.sheetName);
const pt = sheet.PivotTables(1);
const out = [];
const keys = [];
for (const k in pt) keys.push(k);
out.push('keys=' + keys.join(','));
const tryp = (label, fn) => { try { out.push(label + '=' + fn()); } catch (e) { out.push(label + ' ERR ' + e.message); } };
tryp('RowFields', () => pt.RowFields);
tryp('PivotFields.Count', () => pt.PivotFields().Count);
tryp('DataFields', () => pt.DataFields);
tryp('Cache.RecordCount', () => pt.PivotCache().RecordCount);
tryp('Name', () => pt.Name);
tryp('TableRange1', () => pt.TableRange1.Address());
tryp('RefreshTable', () => { pt.RefreshTable(); return 'called'; });
return { dump: out.join(' ;; ') };
